### PR TITLE
fix: updates Kubernetes max version.

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Updates the mass-generate.sh script to consider the v1.31 as the max Kubernetes version.

### CODE REVIEW

**Review by viccuad — APPROVED** [review]

**Comment by viccuad** [comment]
I gave a try for creating the release-1.31 branch, with this exact change, and `./mass-generate.sh -m commit.md --git-dir ~/suse/kw/k8s-objects`, and it was creating all the branches but not the 1.31 for me. Which has me puzzled on how you managed.

**Comment by jvanz** [comment]
> I gave a try for creating the release-1.31 branch, with this exact change, and `./mass-generate.sh -m commit.md --git-dir ~/suse/kw/k8s-objects`, and it was creating all the branches but not the 1.31 for me. Which has me puzzled on how you managed.

I've create the branch only for `v1.31` release. This is my command:

```console
./mass-generate.sh --kube-min-ver 31 --kube-max-ver 31 --git-dir ../k8s-objects -m commit.md 
```

**Comment by flavio** [comment]
You have also to update:
* https://github.com/kubewarden/k8s-objects-generator/blob/cf44df46a57943eb5e4c6fe78cc2f4c7c025301c/mass-push.sh#L12

**Comment by viccuad** [comment]
For me, run locally, I don't get a `release-1.31` branch that `mass-push.sh` can push.

**Comment by jvanz** [comment]
Okay, the problem is that when creating  the `release-1.30` branch, there is no change from the current branch. Therefore, the commit command fail due an empty change set and exiting the script before running the loop for the `1.31` release.

**Review by flavio — APPROVED** [review]
LGTM, thanks for the fix!

**Review by viccuad — APPROVED** [review]

**Pull request merged**
